
{{- range $.Values.servers }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets
  namespace: argocd
spec:
  project: default
  source:
    chart: {{ $.Values.secrets.chart | quote }}
    repoURL: {{ $.Values.secrets.repoURL | quote }}
    targetRevision: {{ $.Values.secrets.targetRevision | quote }}
    helm:
        releaseName: external-secrets
  destination:
    namespace: default
    server: {{ . | quote }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
{{- end }}